version: "3.9"

services:
  server:
    build:
      context: .
    environment:
      MONGODB_URL: mongodb://mongo:2701/website
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/website
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - postgres

  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_DATABASE: website
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: website
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  postgres-data:
